#! /bin/bash

declare -r scriptdir=$(dirname $(readlink -ef $0))

for config in conf/{env,mirrors,cowbuilder} ; do
   source ${scriptdir}/${config}
done

MYPBOPTIONS=(
    ${PBUILDEROPTS[@]}
    ${COWBUILDEROPTS[@]}
)

cmd=$1
arch=$2

MYPBOPTIONS+=(
    "--basepath     ${WORKBASE}/base.cow-${arch}"
)

case $cmd in
    update)
	sudo cowbuilder --update ${MYPBOPTIONS[@]}
	;;
    login)
	sudo cowbuilder --login --save ${MYPBOPTIONS[@]}
	;;
    *)
	echo "Usage: $0 update|login [architecture]"
	exit 1
	;;
    *)
	
esac

