#! /bin/bash

declare -r scriptdir=$(dirname $(readlink -ef $0))

for config in conf/{env,mirrors,cowbuilder} ; do
    source ${scriptdir}/${config}
done

MYPBOPTIONS=(
    ${PBUILDEROPTS[@]}
    ${COWBUILDEROPTS[@]}
)

cmd=$1
arch=$2

if [[ -n $arch ]] ; then
    MYPBOPTIONS+=(
        "--basepath     ${WORKBASE}/base.cow-${arch}"
    )
fi

case $cmd in
    update)
        sudo cowbuilder --update ${MYPBOPTIONS[@]}
        ;;
    login)
        sudo cowbuilder --login --save ${MYPBOPTIONS[@]}
        ;;
    *)
        echo "Usage: $0 update|login [architecture]"
        exit 1
        ;;
esac

# Local variables:
# coding: utf-8
# mode: sh-shell
# End:
