#! /bin/bash

set -e

declare -r scriptdir=$(dirname $(readlink -ef $0))

declare -ra modules=(
    conf/{env,mirrors,errors}
    lib/{common,utils,modules,pbuilder}
)

##########
# Real operation starts
##############################
for module in ${modules[@]}; do
    source ${scriptdir}/$module
done

[[ $EUID -eq 0 ]] && die "Don't build package with privileged user"

OPTS=$(getopt -n $0 \
              -o 'a:d:l:n:u:bhp' \
              --long arch:,dsc:,changelog:,package:,upload:,build,help,pbuilder \
              -- "$@")

[[ $? -eq 0 ]] || die EOPTS "Sorry! I don't understand!!!"

eval set -- "${OPTS}"

while : ; do
    case $1 in
        -a|--arch)
            ARCH=$2
            shift 2
            ;;
        -d|--dsc)
            dsc=$2
            shift 2
            ;;
        -l|--changelog)
            changelog=$2
            shift 2
            ;;
        -n|--package)
            package=$2
            shift 2
            ;;
        -u|--upload)
            uhost=$2
            shift 2
            ;;
        -b|--build)
            build_pkg=1
            shift
            ;;
        -p|--pbuilder)
            build_pkg_via_pbuilder=1
            shift
            ;;
        -h|--help)
            printHelp
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            printHelp
            shift
            ;;
    esac
done

contains ARCH ARCHITECTURES || die EARCH "$ARCH is an unsupported architecture"

source ${scriptdir}/conf/cowbuilder

# set default changelog
[[ -z $changelog ]] && changelog="Rebuild on ${ARCH} via build script ${0##*/}"

if [[ -n ${package} ]] ; then
    aptGetSource
elif [[ -n ${dsc} ]] ; then
    downloadDebianSrc
else
    die EOPTS "'-n' or '-d' is mandatory option"
fi

# add a blocking lock
lockScript
printBuildInfo
prepareBuild

createPbuilderChroot
# everything else beyond '--' in command line goes to buildPackage function
buildPackage $@
uploadArtifacts
# release the lock
unlockScript

# Local variables:
# coding: utf-8
# mode: sh-shell
# End:
# vim: number tabstop=4 softtabstop=4 expandtab
