#! /bin/bash

# DDE specific settings
declare -ra DDE_COMPONENTS=(
    dde-account-faces
    dde-api
    dde-calendar
    dde-control-center
    dde-daemon
    dde-desktop
    dde-dock
    dde-file-manager
    dde-help
    dde-launcher
    dde-session-ui
    libdui
    startdde
)

declare -rA CHECKOUT_BRANCH=(
    [dbus-factory]=raccoon
    [dde-api]=raccoon
    [dde-control-center]=raccoon
    [dde-daemon]=raccoon
    [dde-desktop]=raccoon
    [dde-dock]=raccoon
    [dde-launcher]=raccoon
    [dde-session-ui]=raccoon
    [deepin-desktop-base]=raccoon
    [deepin-desktop-schemas]=raccoon
    [deepin-installer]=loongson
    [deepin-mutter]=release/3.20
    [startdde]=raccoon
    [lastore-daemon]=raccoon
)
