#! /bin/bash

declare -ra dde_components=(
    dde-account-faces
    dde-api
    dde-calendar
    dde-control-center
    dde-daemon
    dde-desktop
    dde-dock
    dde-file-manager
    dde-help
    dde-launcher
    dde-session-ui
    libdui
    startdde
)

declare -ra raccoon_components=(
    dbus-factory
    dde-api
    dde-control-center
    dde-daemon
    dde-desktop
    dde-dock
    dde-launcher
    dde-session-ui
    deepin-desktop-base
    deepin-desktop-schemas
    startdde
)
