#! /bin/bash

declare -Ar MIRRORSITE=(
    [mipsel]='http://s135.sh.deepin.cn/mipsel'
    [mips64el]='http://s135.sh.deepin.cn/mips64el-deepin'
)

declare -Ar OTHERMIRROR=(
    [mipsel]='deb http://s135.sh.deepin.cn/mipsel-experimental raccoon main'
    [mips64el]=''
)

declare -Ar UPSTREAMREPO=(
    [mips64el]='http://s135.sh.deepin.cn/mips64el-debian'
)
