#! /bin/bash

declare -Ar color=(
    ['reset']='\e[0m'
    ['error']='\e[1m\e[31m'
    ['info']='\e[1m\e[32m'
    ['warn']='\e[1m\e[33m'
)

die() {
    echo -e "${color[error]}E:${color[reset]} $BASH_LINENO: $@" >&2
    exit 1
}

info() {
    echo -e "${color[info]}I:${color[reset]} $@"
}

warn() {
    echo -e "${color[warn]}W:${color[reset]} $@"
}

printVersion() {
    echo "$0 version $SVERSION"
    exit 0
}

hasBin() {
    local executable=$1
    if [[ -n $(type $1) ]] ; then
        return 0
    else
        return 1
    fi
}

hasPackage() {
    local pkg=$1
    if dpkg-query -f '${binary:Package}\n' -W | grep -wqs $pkg ; then
        return 0
    else
        return 1
    fi
}

loadModule() {
    local mods=${@}
    for module in ${mods} ; do
        if [[ -f ${module} ]] ; then
            source ${module}
        else
            die "Not able to load ${module}"
        fi
    done
}

assert() {
    local ret
    eval ret=\$${1}
    [[ -n $ret ]] || die "I'm confused, var: ${1} is empty"
}

pushd() {
    builtin pushd $@ >& /dev/null
}

popd() {
    builtin popd $@ >& /dev/null
}

createdir() {
    local dir=$1
    local desc=$2
    if [[ ! -d ${dir} ]];then
        info "create $2 directory: $dir"
        mkdir -p $dir
    fi
}
