#! /bin/bash

# download debian src
aptGetSource() {
    local aptcache=
    local aptdir=${scriptdir}/apt

    local apt_options="-o Dir::Etc=${aptdir} \
        -o Dir::Etc::sourcelist=sources.list-${ARCH} \
	    -o Dir::Etc::SourceParts=/dev/null \
	    -o Dir::State=${aptdir}/state \
	    -o Dir::Cache=${aptdir}/cache \
	    -o Debug::NoLocking=true \
	    -o Acuqire::Retries=5 \
	    -o APT::Architecture=${ARCH} \
	    -o APT::Default-Release=${DISTRIBUTIONS[${ARCH}]} \
	    -o APT::Get::Assume-Yes=true \
	    -o APT::Get::AllowUnauthenticated=true"

    mkdir -pv ${aptdir}/state/lists/partial

    # create sources.list
    cat <<EOF > ${aptdir}/sources.list-${ARCH}
deb [lang=en] ${UPSTREAMREPO[$ARCH]} ${DISTRIBUTIONS[${ARCH}]} main contrib non-free
deb-src [lang=en] ${UPSTREAMREPO[$ARCH]} ${DISTRIBUTIONS[${ARCH}]} main contrib non-free
EOF
    # update package index
    apt-get ${apt_options} update

    aptcache=$(apt-cache ${apt_options} showsrc $package)
    # get package name and package version
    package=$(echo "${aptcache}" | awk '/^Package:/ {print $2; exit}')
    version=$(echo "${aptcache}" | awk -F: '/^Version:/ {gsub(/ /, "", $NF); ver=$NF} END {print ver}')

    # download debian source code
    createWorkdir

    pushd ${workdir}
    apt-get ${apt_options} source --download-only ${package}
    popd
}

downloadDebianSrc() {
    local odscfile=$(basename ${dsc})
    local dscfile=$(urlDecode $odscfile)

    package=${dscfile%%_*}
    version=$(echo ${dscfile//.dsc} | sed -e "s/${package}_//")

    createWorkdir

    if checkValidURL $dsc ; then
        hasBin dget || die EPACKAGE "Missing devscripts in the system"
        pushd ${workdir}
        dget -d -u ${dsc}
        # rename dscfile
        [[ $odscfile == $dscfile ]] || mv $odscfile $dscfile
        popd
    elif [[ -f $dsc ]] ; then
        # $dsc is a local file
        cp ${dsc} ${workdir}/
        local linenum=1
        local dscpath=$(dirname ${dsc})
        dscline=$(tail -n ${linenum} ${dsc} | head -1)
        while [[ x${dscline} != x'Files:' ]] ; do
            local srcfile=$(echo ${dscline} | awk '{print $3}' )
            if [[ -f ${dscpath}/${srcfile}  ]] ; then
                cp ${dscpath}/${srcfile} ${workdir}/
            else
                die EACCESS "Not able to find ${srcfile} in ${dscpath}"
            fi
            linenum=$(echo $linenum + 1 | bc)
            dscline=$(tail -n ${linenum} ${dsc} | head -1)
        done
    fi

    [[ -f ${workdir}/${dscfile} ]] || \
        die EACCESS "Not able to find ${dscfile} in ${workdir}"
    dsc=$dscfile
}

prepareBuild() {
    local srcdir=${workdir}/${package}-${version}

    info "clean up $srcdir"
    rm -rf $srcdir

    if [[ -z $dsc ]] ; then
        dsc=${package}_${version}.dsc
    fi

    if [[ -f ${workdir}/${dsc} ]] ; then
        dpkg-source -x ${workdir}/${dsc} ${srcdir}
    else
        die EACCESS "Fail to read Debian source control file"
    fi
}

buildPackage() {
    pushd ${workdir}/${package}-${version}

    # return unless we want to build a package
    [[ ${build_pkg} -eq 1 ]] || \
        [[ ${build_pkg_via_pbuilder} -eq 1 ]] || return 0

    local hookdir=${scriptdir}/hooks.d/debuild
    # pbuilder will copy hooks into chroots
    [[ ${build_pkg_via_pbuilder} ]] && hookdir=/tmp/hooks

    dch -a -D ${DISTRIBUTIONS[$ARCH]} "${changelog}"

    case ${ARCH} in
        sw_64)
            warn "Add a hooks for ${ARCH} platform"
            DEBBUILDOPTS+=" --hook-init=${hookdir}/sw64-check-sw64ize.hook"
            DEBBUILDOPTS+=" --hook-build=${hookdir}/sw64-fix-arch.hook"
            ;;
    esac

    # function parameter should override DEBBUILDOPTS
    DEBBUILDOPTS+=" $@"

    if [[ $build_pkg -eq 1 ]] ; then
        info "Checking build dependencies:"
        if dpkg-checkbuilddeps -a ${ARCH} debian/control; then
            info "Build dependencies satisfied"
        else
            die EDEPS "Build dependencies unsatisfied"
        fi

        info "buildpackage with options: ${DEBBUILDOPTS}"
        eval dpkg-buildpackage ${DEBBUILDOPTS}
    else
        eval pdebuild --pbuilder cowbuilder  \
             --use-pdebuild-internal         \
             --debbuildopts '"${DEBBUILDOPTS}"' \
             ${PBUILDEREXTRAOPTS[@]}         \
             --                              \
             ${PBUILDEROPTS[@]}              \
             ${COWBUILDEROPTS[@]}
    fi

    popd
}

uploadArtifacts() {
    [[ -z $uhost ]] && return 0
    hasBin dput || die EPACKAGE "Missing dput in the system!!!"
    dput -uf ${uhost} $(ls -At ${workdir}/*.changes| head -n 1)
}
